### ISSUE TITLE
Corrected_LongRead.fa missing formatting !

### ISSUE THREAD

**Issue by jnarayan81** [NDBL/HECIL#4]
I test run your sample LongReads.fa
➜  HECIL git:(master) ✗ python HECIL.py -l LongRead.fa -s ShortRead.fq -len 202 -o Out
Started running alignment
[samopen] SAM header is present: 55 sequences.
-e Finished running alignment

Started running correction
-e Finished running correction

-e Generating output file with all (corrected and uncorrected) reads

-e Finished running HECIL

I notice the outfile "Corrected_LongRead.fa" is not formatted correctly, specially first sequence is missing the fasta header (attached). Did I missed something?

[Corrected_LongRead.fa.txt](https://github.com/NDBL/HECIL/files/2293480/Corrected_LongRead.fa.txt)
[Out.txt](https://github.com/NDBL/HECIL/files/2293482/Out.txt)

**Comment by ochoudhu** [comment]
Thanks for pointing this out. The inconsistency was caused by reads that spanned multiple lines. It should work now.
